const proofread = str => str.toLowerCase()
                            .replace(/ie/g, 'ei')
                            .split('. ')
                            .map(item => item.charAt(0).toUpperCase() + item.slice(1))
                            .join('. ')